import type { Metadata } from "next";
import { Lato, Libre_Caslon_Text } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const horizon = localFont({
  src: "./fonts/horizon.otf",
  variable: "--font-horizon",
  weight: "100 900",
});
const horizonOutlined = localFont({
  src: "./fonts/horizon_outlined.otf",
  variable: "--font-horizon-outlined",
  weight: "100 900",
});
const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
  weight: ["300", "400", "700"],
});
const caslon = Libre_Caslon_Text({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-caslon",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${horizon.variable} ${horizonOutlined.variable} ${lato.variable} ${caslon.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
